name: saisonier
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5
  go_router: ^14.0.0
  pocketbase: ^0.18.0
  drift: ^2.14.0
  drift_flutter: ^0.1.0
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  cached_network_image: ^3.3.0
  google_fonts: ^6.1.0
  sensors_plus: ^7.0.0
  wakelock_plus: ^1.4.0
  path: ^1.9.1
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.0.0
  http: ^1.6.0
  image_picker: ^1.0.7
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.5.4
  riverpod_generator: ^2.4.0
  drift_dev: ^2.14.0
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  mockito: ^5.4.6
  sqlite3: ^2.9.4
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
